/* DO NOT EDIT THIS FILE - it is machine generated */
#include <Java/include/jni.h>
/* Header for class moss_mokka_Texture */

#ifndef _Included_moss_mokka_Texture
#define _Included_moss_mokka_Texture
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     moss_mokka_Texture
 * Method:    bind
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_Mokka_Texture_bind
  (JNIEnv *, jobject, jint);

/*
 * Class:     moss_mokka_Texture
 * Method:    unbind
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Mokka_Texture_unbind
  (JNIEnv *, jobject);
  

  void bindTexture(JNIEnv*, jobject, int);

  void unbindTexture(JNIEnv*, jobject);

/*
 * Class:     Mokka_Texture
 * Method:    createTexture
 * Signature: (Ljava/lang/String;)Lmoss/mokka/Texture;
 */
JNIEXPORT jobject JNICALL Java_Mokka_Texture_createTexture
  (JNIEnv *, jclass, jstring);

  jobject createTexture(JNIEnv*, jclass, const char*);

#ifdef __cplusplus
}
#endif
#endif
