/* DO NOT EDIT THIS FILE - it is machine generated */
#include <Java/include/jni.h>
#include "mka_VertexArray.h"
#include "mka_Shader.h"
#include "mka_VertexBufferLayout.h"
#include "mka_Texture.h"
#include <glm/glm.hpp>
#include <glm/gtc/matrix_transform.hpp>
/* Header for class moss_mokka_Rect */

#ifndef _Included_moss_mokka_Rect
#define _Included_moss_mokka_Rect





jobject getShapeVa(JNIEnv*, jobject);

void bindShapeVa(JNIEnv*, jobject);

glm::mat4 getShapeTranslationMatrix(JNIEnv*, jobject);

jobject getShapeParent(JNIEnv*, jobject);

IndexBuffer getShapeIb(JNIEnv* , jobject );

void bindShapeIb(JNIEnv* , jobject );

jobject getShapeMaterial(JNIEnv* , jobject);

void bindShapeMaterial(JNIEnv*, jobject);

#ifdef __cplusplus
extern "C" {
#endif


/*
 * Class:     Mokka_Shape
 * Method:    translate
 * Signature: (FFF)V
 */
JNIEXPORT void JNICALL Java_Mokka_Shape_translate
  (JNIEnv *, jobject, jfloat, jfloat, jfloat);


#ifdef __cplusplus
}
#endif
#endif
