/* DO NOT EDIT THIS FILE - it is machine generated */
#include <Java/include/jni.h>
/* Header for class moss_mokka_VertexArray */

#ifndef _Included_moss_mokka_VertexArray
#define _Included_moss_mokka_VertexArray
#ifdef __cplusplus
extern "C" {
#endif


void glEnableDefaultBlending();

/*
 * Class:     moss_mokka_VertexArray
 * Method:    glEnableDefaultBlending
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Mokka_VertexArray_glEnableDefaultBlending
  (JNIEnv *, jclass);

/*
 * Class:     moss_mokka_VertexArray
 * Method:    GenID
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Mokka_VertexArray_GenID
  (JNIEnv *, jclass);

/*
 * Class:     moss_mokka_VertexArray
 * Method:    AddBuffer
 * Signature: (Lmoss/mokka/VertexBuffer;J)V
 */
JNIEXPORT void JNICALL Java_Mokka_VertexArray_AddBuffer
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     moss_mokka_VertexArray
 * Method:    Destruct
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Mokka_VertexArray_Destruct
  (JNIEnv *, jobject);

/*
 * Class:     moss_mokka_VertexArray
 * Method:    Bind
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Mokka_VertexArray_Bind
  (JNIEnv *, jobject);

/*
 * Class:     moss_mokka_VertexArray
 * Method:    UnBind
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Mokka_VertexArray_UnBind
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
