/* DO NOT EDIT THIS FILE - it is machine generated */
#include "Mokka.h"
#include <jni.h>
/* Header for class Mokka_Window */

#ifndef _Included_Mokka_Window
#define _Included_Mokka_Window
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     Mokka_Window_TwoD
 * Method:    setOrthoCoords
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_Mokka_Window_00024TwoD_setOrthoCoords
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat);

  /*
* Class:     Mokka_Window
* Method:    setOrthoCoords
* Signature: (FFF)V
*/
JNIEXPORT void JNICALL Java_Mokka_Window_translateCamera
    (JNIEnv*, jclass, jfloat, jfloat, jfloat);



 /*
 * Class:     Mokka_Window
 * Method:    getCameraX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_Mokka_Window_getCameraX
  (JNIEnv* , jclass);

 /*
 * Class:     Mokka_Window
 * Method:    getCameraY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_Mokka_Window_getCameraY
  (JNIEnv* , jclass);


/*
 * Class:     Mokka_Window
 * Method:    clear
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Mokka_Window_clear
  (JNIEnv *, jclass);

/*
 * Class:     Mokka_Window
 * Method:    shouldClose
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_Mokka_Window_shouldClose
  (JNIEnv *, jclass);

/*
 * Class:     Mokka_Window
 * Method:    setPos
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_Mokka_Window_setPos
  (JNIEnv *, jclass, jint, jint);

   /*
 * Class:     Mokka_Window
 * Method:    GetWidth
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_Mokka_Window_getWidth
  (JNIEnv* , jclass);

   /*
 * Class:     Mokka_Window
 * Method:    GetHeight
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_Mokka_Window_getHeight
  (JNIEnv* , jclass);

/*
 * Class:     Mokka_Window
 * Method:    pollAndSwap
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Mokka_Window_pollAndSwap
  (JNIEnv *, jclass);

/*
 * Class:     Mokka_Window
 * Method:    terminate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Mokka_Window_terminate
  (JNIEnv *, jclass);

  /*
 * Class:     Mokka_Window
 * Method:    draw
 * Signature: (LMokka/Shape;)V
 */
JNIEXPORT void JNICALL Java_Mokka_Window_draw
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
