/* DO NOT EDIT THIS FILE - it is machine generated */
#include <Java/include/jni.h>
#include "mka_Renderer.h"
#include <glm/glm.hpp>
#include <glm/gtc/matrix_transform.hpp>
/* Header for class moss_mokka_Maths */
  
  


#ifndef _Included_moss_mokka_Maths
#define _Included_moss_mokka_Maths



#ifdef __cplusplus
extern "C" {
#endif


/*
 * Class:     moss_mokka_Shader
 * Method:    bind
 * Signature: (FFFFFF)J
 */
JNIEXPORT jlong JNICALL Java_Mokka_Maths_CreateOrthoMatrix
  (JNIEnv *, jclass, jfloat x1, jfloat x2, jfloat y1, jfloat y2, jfloat z1, jfloat z2);



  #ifdef __cplusplus
}
#endif
#endif