/* DO NOT EDIT THIS FILE - it is machine generated */
#include <Java/include/jni.h>
/* Header for class moss_mokka_VertexBuffer */

#ifndef _Included_moss_mokka_VertexBuffer
#define _Included_moss_mokka_VertexBuffer
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     moss_mokka_VertexBuffer
 * Method:    gen
 * Signature: ([FI)I
 */
JNIEXPORT jint JNICALL Java_Mokka_VertexBuffer_gen
  (JNIEnv *, jobject, jfloatArray, jint);

/*
 * Class:     moss_mokka_VertexBuffer
 * Method:    Destruct
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Mokka_VertexBuffer_Destruct
  (JNIEnv *, jobject);

/*
 * Class:     moss_mokka_VertexBuffer
 * Method:    Bind
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Mokka_VertexBuffer_Bind
  (JNIEnv *, jobject);

/*
 * Class:     moss_mokka_VertexBuffer
 * Method:    UnBind
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Mokka_VertexBuffer_UnBind
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
